apiVersion: v1
kind: Secret
metadata:
  name: larafleet-secret
  namespace: larafleet
type: Opaque
stringData:
  APP_KEY: "base64:HWifQfSmulkKWK9Flny/sJzlW5+BJ38znam1ppji08E="
  DB_USERNAME: "larafleet"
  DB_PASSWORD: "secret"
  MYSQL_ROOT_PASSWORD: "secret"
